export default {
  'hasSection8.label':        'Do you have Section 8 Housing?',
  'hasSection8.hint':         'Section 8 provides rental housing assistance.',
  'hasSnap.label':            'Do you have SNAP?',
  'hasSnap.hint':             'SNAP provides assistance with buying food',
  'hasEarnedIncome.label':    'Do you have earned income?',
  'hasEarnedIncome.hint':     'Earned income is income from wages or self-employment',
  'hasTAFDC.label':           'Do you have TAFDC?',
  'hasTAFDC.hint':            'Transitional Aid to Families with Dependent Children provides short-term financial assistance to families with children',
  'hasSSI.label':             'Do you have SSI?',
  'hasSSI.hint':              'Supplemental Security Income is a federal program that provides financial and health care assistance to people 65 and over, or people who are blind or disabled',
  'hasSSDI.label':            'Do you have SSDI?',
  'hasSSDI.hint':             'Social Security Disability Income is a federal program to help people with disabilities',
  'hasChildSupport.label':    'Do you receive child support?',
  'hasChildSupport.hint':     'Child support is money paid to you by a former spouse to help your child',
  'hasUnemployment.label':    'Do you receive unemployment benefits?',
  'hasUnemployment.hint':     'Unemployment benefits provide income to people who have been laid off',
  'hasWorkersComp.label':     'Do you receive Workers Compensation?',
  'hasWorkersComp.hint':      'Workers Compensation provides assistance for people who have been injured on the job',
  'hasPension.label':         'Do you have a pension?',
  'hasPension.hint':          'A pension provides income to retirees, usually from their former employers',
  'hasSocialSecurity.label':  'Do you have Social Security Income?',
  'hasSocialSecurity.hint':   'Social Security is a federal program that provides assistance to retirees',
  'hasAlimony.label':         'Do you receive alimony?',
  'hasAlimony.hint':          'Alimony is money paid by one spouse to the other after a divorce',
  'hasOtherIncome':           'Do you have other income?',
  'hasOtherIncome':           'Please note income you may have from sources that are not listed above',
};
