const clientList = [
  {
    name: 'John H.',
    lastVisit: '1 May 2017',
    id: 12345,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/matthew.png',
    dob: '1/1/1997',
    zipCode: '02210',
    visits: [
        {
            date: '7/14/16',
            benefits: 'SNAP, MassHealth, Section 8'
        },
        {
            date: '5/1/17',
            benefits: 'SNAP, MassHealth'
        },
    ],
  },
  {
    name: 'Sarah M.',
    lastVisit: '12 June 2016',
    id: 54321,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/jenny.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Matt A.',
    lastVisit: '5 Jan 2017',
    id: 36895,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/matthew.png',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Mark G.',
    lastVisit: '4 May 2017',
    id: 47986,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/daniel.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Molly P.',
    lastVisit: '28 Feb 2016',
    id: 14789,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/molly.png',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'John J.',
    lastVisit: '1 May 2017' ,
    id: 85694,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/steve.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Amelia E.',
    lastVisit: '1 Oct 2015' ,
    id: 32475,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/molly.png',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Jill E.',
    lastVisit: '1 May 2017' ,
    id: 98657,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/jenny.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Bill C.',
    lastVisit: '1 May 2017' ,
    id: 47965,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/matthew.png',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Jeff K.',
    lastVisit: '16 May 2017' ,
    id: 79134,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/steve.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Sally V.',
    lastVisit: '1 Nov 2016' ,
    id: 49381,
    image: 'http://react.semantic-ui.com/assets/images/avatar/large/jenny.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  },
  {
    name: 'Jim Y.',
    lastVisit: '1 Dec 2015' ,
    id: 36941,
    image:'http://react.semantic-ui.com/assets/images/avatar/large/daniel.jpg',
    dob: '1/1/1997',
    zipCode: '02210',
    visits:[],
  }
]

export {clientList};